### ISSUE TITLE
sqlite3.OperationalError: no such table: timetable

### ISSUE THREAD

**Issue by engrmafzaalch** [teja156/microsoft-teams-class-attender#1]
Facing this issue 
OS: Kubuntu 18.04
![image](https://user-images.githubusercontent.com/54806555/97289073-83b0ce80-1868-11eb-8653-9673bb930820.png)

**Comment by engrmafzaalch** [comment]
`
#Database path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
db_path = os.path.join(BASE_DIR, "timetable.db")
print(db_path)

`

**Comment by NmaburiNarayana** [comment]
did you got the solution for the issue

**Comment by engrmafzaalch** [comment]
@NmaburiNarayana  yes Actually this is issue of .db file path 
instead of `conn = sqlite3.connect("timetable.db)` make a variable of db_path using os path system
`BASE_DIR = os.path.dirname(os.path.abspath(__file__))`
`db_path = os.path.join(BASE_DIR, "timetable.db")`
and now use `sqlite3.connect(db_path)`

**Comment by NmaburiNarayana** [comment]
![image](https://user-images.githubusercontent.com/61817529/97293959-5c133380-1873-11eb-9fe0-45ea318dfd26.png)
do u know the soluion for this error

**Comment by engrmafzaalch** [comment]
1. Install Chrome Driver: sudo apt install chromium-chromedriver
2. Update your chrome to chrome 86

**Comment by NmaburiNarayana** [comment]
i have done that and facing the same issue
