### ISSUE TITLE
presenter sets all the permission and if wait time in lobby is more, the program crashes

### ISSUE THREAD

**Issue by VivanVatsa** [teja156/microsoft-teams-class-attender#10]
presenters (Professors) are in control of all the permissions, whom they want to let it in or whom they don't.
if the wait time in the lobby is more than 8 - 10 mins, the program crashes.
there has to be some reverse refresh loop problem ??

**Comment by amalthomas-exe** [comment]
Try increasing the timeout duration
`try_time = int(start_time.split(":")[1]) + <preferred duration>`

**Comment by VivanVatsa** [comment]
tried splitting with preferred duration. no luck still

**Comment by amalthomas-exe** [comment]
Sorry I missed a point
edit the following code also:
`k = 1
while(k<=15):          #change 15 to an higher integer
    print("Join button not found, trying again")
    time.sleep(60)
    driver.refresh()`

**Comment by VivanVatsa** [comment]
oh okay. now i got it.
closing the issue now

**Comment by pranav-05** [comment]
I think in such we have to change the code in such way that bot does not leaves the meeting/class until the attandance becomes 50% of total.
