### ISSUE TITLE
Unable to bypass the permission popup

### ISSUE THREAD

**Issue by amalthomas-exe** [teja156/microsoft-teams-class-attender#13]
I was unable to bypass the popup which asked for permission to use the mic and speakers. Leading to the program to end abruptly. 
Looks like we need to update the code a little bit. Also was not able to get the id/name/ class name of the allow button in the popup.

**Comment by aymenkrifa** [comment]
If you found how to get rid of this problem, please share :)

**Comment by amalthomas-exe** [comment]
Basically, I was using the edge browser, but this program was meant to run on the chrome browser. Since we have already permitted the Chrome browser to access the mic and camera in the additional arguments option, no popup came up and I was able to join the class smoothly.
