### ISSUE TITLE
you are explicitly telling it to wait for five seconds after clicking on a anchor tag?

### ISSUE THREAD

**Issue by sanidhyajain1** [teja156/microsoft-teams-class-attender#18]
cant u make a event handler and proceed only when its loaded....because if u have slow wifi the the page might take more than 5 seconds to load and no such web element would be found and it would terminate the process

**Comment by cursedsoulofgods** [comment]
You can adjust the delay in the code block, can't you?
@sanidhyajain1

**Comment by cursedsoulofgods** [comment]
@sanidhyajain1 Which function are you talking about?

**Comment by sanidhyajain1** [comment]
nvm...i read the documentaion and the "wait" function is da one that i was looking for

**Comment by cursedsoulofgods** [comment]
Please close this issue @sanidhyajain1 if you are done with it. 
Regards,
Sumangalam

**Comment by sanidhyajain1** [comment]
hey i was taking a look at ur code(im new to selenium)...i saw that ur using something called timetable.db can u please tell me what that is 
i use js btw

**Comment by cursedsoulofgods** [comment]
Timetable.db is a local database sql file. It is just a database file which is storing the data of time table and the times. Just like excel does but way better.
The code belongs to @teja156!

**Comment by amalthomas-exe** [comment]
@sanidhyajain1 if your problem has been resolved, can u please close this issue

**Comment by sanidhyajain1** [comment]
ok
