### ISSUE TITLE
Zoom setup

### ISSUE THREAD

**Issue by Spidy104** [teja156/microsoft-teams-class-attender#19]
Is it possible to do something like this in zoom as my classes are held in zoom that is why I was asking if possible can tell some tweaks?

**Comment by Shravan-1908** [comment]
Checkout my repository, I've already done that: https://github.com/Shravan-1908/online-class-bot
Make sure you install modules ```pyautogui``` and ```win10toast``` before using the code. You can modify the timetable according to your needs.

**Comment by Spidy104** [comment]
Thanks

**Comment by Shravan-1908** [comment]
Also ensure that zoom application is launched before you run the code. Close the issue now.

**Comment by Spidy104** [comment]
Okk but the teams application was better then or else I can call for the subprocess module to just do the job for me, without me opening the app is it good then?

**Comment by Shravan-1908** [comment]
You can use the ```startfile``` method from ```os``` module to do the same. For ex:
```
from os import startfile
startfile(r"ABSOLUTE PATH TO ZOOM.EXE")
```

**Comment by Spidy104** [comment]
thanks, btw can you do a python tutorial from beginner to advanced as I am really liking your projects.
________________________________

**Comment by Shravan-1908** [comment]
Thanks for the appreciation, I've learnt everything from YouTube. Visit **CodeWithHarry** on YouTube, he has some really high quality content. Link to his full beginner to advanced python tutorial: https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME

**Comment by Spidy104** [comment]
Sure, Can you recommend me a good editor for python, I currently use.
OS:WINDOWS 10

**Comment by irfgrouppvt** [comment]
requirements

and steps to fulfill the requirements

**Comment by Spidy104** [comment]
Research it out, give a few tweaks and then you are done, research on some of the modules that would be helpful in automation Ig.

**Comment by Shravan-1908** [comment]
Already mentioned in the README of the repo.
Still,
- ```pip install pyautogui```
- ```pip install win10toast```
- Zoom application and it's full path to .exe
