### ISSUE TITLE
Design a bot for Zoom

### ISSUE THREAD

**Issue by irfgrouppvt** [teja156/microsoft-teams-class-attender#21]
Kindly design a bot attender for zoom

**Comment by irfgrouppvt** [comment]
> Kindly design a bot attender for zoom

@teja156

LABEL - new feature request

**Comment by amalthomas-exe** [comment]
you got me.
I'm working on it.

**Comment by Shravan-1908** [comment]
Already solved: https://github.com/teja156/microsoft-teams-class-attender/issues/19

**Comment by amalthomas-exe** [comment]
@Shravan-1908 ok

**Comment by Shravan-1908** [comment]
Close this issue now.

**Comment by irfgrouppvt** [comment]
> Close this issue now.

CLOSED
