### ISSUE TITLE
with a timetable constraint, it's difficult to train the bot to connect to classes

### ISSUE THREAD

**Issue by VivanVatsa** [teja156/microsoft-teams-class-attender#26]
many institutes don't have a designated timetable to follow for lectures, so the wait time for the bot needs to have different parameters than the day's schedule.
got any ideas on how to do it?
searching for a distinct different parameter to make it schedule independently from the days one.

**Comment by catatonicprimes** [comment]
make the people use a synchronized calender with the timetable , that
further would be synced to the bot

or rather can

many of them institutions send joining links , one can make the bot to read
specific keystrings in the joining link messages and can join the classes ,
without the need of a synced calender
